### ISSUE TITLE
Thorough Example

### ISSUE THREAD

**Issue by stoianmihail** [InitialDLab/SampleJoin#1]
Is there a way to provide 2 csv files (containing two tables) and get a sample join of, e.g., 100K tuples?
Example: `./sj t1.csv t2.csv 100000`
It would be great to have a small example how this could be achieved!
Thanks!

**Comment by zzy7896321** [comment]
Hi Mihail,

I think run_QA() in tpcds_sample_queries.cpp is a good starting point. Unfortunately, most of the things are coded in the c++ code. If you want to use file name from the command line, you'll have to write some code to read from the command line options.

The following is a detailed instruction of how to modify the code to run a join between two csv files
Assuming you have two csv files t1.csv and t2.csv with k_1, k_2 columns respectively. And suppose your join columns are columns j_1 and j_2 in the two csv files and you want all the columns of both tables to appear in the final result. The things you'll need modify are:

1. On line 103, plug in the number of samples you want between { and }. For each specified sample count, an independent sample of join results of the count will be created.

2. Lines 111 to 160 specify the input csv. You need to create two Int64CSVTable instances for t1.csv and t2.csv. For example, suppose t1.csv has 4 columns, it will look like this:

auto t1_table = std::make_shared<Int64CSVTable>();
if (!t1_table->load(settings.data_path + "t1.csv", {1, 2, 3, 4}, ',')) {
  return false;
}

The {1, 2, 3, 4} part specifies which columns you want to load, and the first column is numbered 1; the second is 2, and so on.

3. Lines 175 - 209 specify what the query is. JefastBuilder is where we first specify the join query graph and then build the join data graph based on that. The join query graph is created using AppendTable() and AddTableToFork() functions (there are docs in database/jefastBuilder.h). In your specific case, you'd want to write

// the fourth arg to AppendTable is ignored and may be omitted
// j_1 is the join column in t1_table, and j_2 is the join column in t2_table
// Here column numbers start from 0, and are column numbers in the in memory table loaded from the csv file. (Note the unfortunate mismatch of how columns are numbered in csv and in the in-mem tables).
// E.g., your csv file t1 has 4 columns and you loaded it into an Int64CSVTable by using {1, 2, 3, 4}.
// Then you should use j_1 = 1 here in AppendTable(), not 2!!
auto t1_tno = builder.AppendTable(t1_table, -1, j_1);
auto t2_tno = builder.AppendTable(t2_table, j_2, -1);

4. Line 231 is where we get the join samples in results. The results vector will contain the row numbers for the all tuples in the sample, for all tables in the query. The order of the row numbers are the same as that you appended/added the tables to the query graph. E.g., in your specific case, the row number of the tuple sampled in t1 will be in results[0], and that of t2 will be in results[1]. You may also use the return value of AppendTable()/AddTableToFork() to find the index, e.g., t1_tno and t2_tno (which are 0 and 1).

5. If you want to print out the joining results to an external file, you'll need to do that yourself. You may access individual fields in the tables by using Int64CSVTable.get_int64(row_no, col_no). Again, col_no starts from 0 and that mapping depends on what you passed to Int64CSVTable.load() in the beginning.

Let me know if you have further questions.
Zhuoyue

**Comment by stoianmihail** [comment]
Thanks for the detailed description! I will try it out and let you know if something does not work. Maybe then we can attach the resulting cpp file as an example.
