### ISSUE TITLE
About extended olken

### ISSUE THREAD

**Issue by Leesangoh** [InitialDLab/SampleJoin#4]
Hi, I have a question about this code.

In a generic_sample_test.cpp, where can I find Extended olden code?

I guess it was a baseline experiment, because it uses olkenIndex.

Furthermore, From nowhere, I was not able to find the bound (W(t)) of Extended olken. where can I find it?

**Comment by zzy7896321** [comment]
Yes, the olkenIndex is the one. However, the actual implementation follows the original Olken design: we sample an entire join result before performing the rejection step. The total rejection probability is computed as 1 - product of degrees of the selected tuples / product of max degrees: https://github.com/InitialDLab/SampleJoin/blob/454474287edecfbbb0fc0657e1cfebc59854dc7b/mmJoin/src/database/olkenIndex.h#L87

**Comment by Leesangoh** [comment]
Thanks a lot!
